# Generated by Django 4.0 on 2023-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('Roomtype', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'rooms',
            },
        ),
    ]
