# Generated by Django 4.0 on 2023-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='Room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
