# Generated by Django 4.2.5 on 2023-09-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_rooms_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomtype',
            field=models.CharField(choices=[('Single bed', 'Single bed'), ('Double bed', 'Double bed'), ('More beds', 'More beds')], max_length=30),
        ),
    ]
