# Generated by Django 4.2.5 on 2023-09-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_alter_rooms_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('student_id', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=155, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=60)),
                ('confirm_password', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Employee', 'Employee'), ('Student', 'Student')], max_length=12, null=True)),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
