# Generated by Django 4.2.5 on 2023-09-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0004_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='category',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Student', 'Student')], max_length=12, null=True),
        ),
    ]
